version: '3'
services:
  lru-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lru:v0.1
    working_dir: /opt/apps/
    # command: bash -c " while true ; do sleep 1; echo `date +%Y-%m-%d-%H-%M`" 当前docker-compose只用于build镜像,请执行docker-compose build"; done"
    command: python lru.py
  test-lru-service:
      image: lru:v0.1
      working_dir: /opt/apps/
      command: pytest
  test-performance-service:
    image: lru:v0.1
    working_dir: /opt/apps/
    command: python test_performance.py
  test-log-service:
      image: lru:v0.1
      working_dir: /opt/apps/
      command: bash -c "python lru_log.py &&  eliot-tree *.log"
      volumes: 
        - "$PWD:/opt/apps/"